export type QuestionOption = {
  value: string;
  label: string;
  points: number;
  reportContext?: string;
};

export type Question = {
  id: string;
  domain: string;
  text: string;
  options: QuestionOption[];
};

export type Domain = {
  id: string;
  name: string;
};

export const domains: Domain[] = [
  { id: "section1", name: "Awareness & Maturity" },
  { id: "section2", name: "Drivers & Motivation" },
  { id: "section3", name: "Market Readiness & Trust" },
  { id: "section4", name: "Economics & Decision-Making" },
  { id: "section5", name: "Future Outlook" },
];

const questionsEn: Question[] = [
  // Section 1: Awareness & Maturity (15 points)
    {
      id: "q1",
    domain: "section1",
    text: "How familiar is your organisation with carbon credits?",
      options: [
      { value: "5", label: "Very familiar – active participation in carbon markets", points: 5, reportContext: "Your organization demonstrates advanced market literacy through active carbon credit participation. This positions you well for emerging opportunities in Saudi Arabia's voluntary carbon market." },
      { value: "4", label: "Very familiar – evaluated but not yet participated", points: 4, reportContext: "Your evaluation experience provides a strong foundation. The next step involves transitioning from assessment to execution, potentially starting with pilot transactions." },
      { value: "3", label: "Fairly familiar – exploring options", points: 3, reportContext: "Your exploratory phase is an important first step. Organizations at this stage typically benefit from structured education on VCM mechanics, project types, and transaction processes specific to the KSA context." },
      { value: "1", label: "Aware, but not yet assessed", points: 1, reportContext: "Basic awareness exists but lacks depth. Priority should be given to comprehensive training on carbon credit fundamentals, particularly how they align with Saudi Arabia's Vision 2030 and SGI commitments." },
      { value: "0", label: "Not familiar at all", points: 0, reportContext: "This represents a significant knowledge gap. Immediate action required: foundational education on carbon markets, terminology, and relevance to your sector within the Saudi regulatory landscape." },
      ],
    },
    {
      id: "q2",
    domain: "section1",
    text: "Which best describes your organisation's current climate strategy?",
      options: [
      { value: "5", label: "Net Zero target with interim milestones and governance structure", points: 5, reportContext: "Your comprehensive climate governance framework demonstrates strategic maturity. Carbon credits can now be integrated as a tactical instrument within your established reduction hierarchy, particularly for residual emissions and hard-to-abate sectors." },
      { value: "4", label: "Net Zero target defined but implementation roadmap in development", points: 4, reportContext: "Your Net Zero commitment shows leadership, but the roadmap gap creates uncertainty around carbon credit requirements. Recommended next step: scenario modeling to quantify temporary vs. permanent offsetting needs across your decarbonization timeline." },
      { value: "3", label: "Emissions reduction plan in progress", points: 3, reportContext: "Active reduction planning is positive, but absence of a Net Zero target may signal limited long-term vision. Carbon credits risk becoming a substitute for ambition rather than a complement to reduction. Consider formalizing a science-based target before significant credit procurement." },
      { value: "2", label: "Carbon footprint measured only", points: 2, reportContext: "Measurement without strategy suggests compliance-driven rather than value-driven approach. Your organization should prioritize developing a reduction roadmap where carbon credits serve as a bridge, not a destination." },
      { value: "0", label: "No formal climate strategy yet", points: 0, reportContext: "Absence of climate strategy indicates carbon credits are premature. Focus first on baseline measurement and materiality assessment to understand which emissions sources warrant offset consideration versus reduction investment." },
      ],
    },
    {
      id: "q3",
    domain: "section1",
    text: "Has your organisation conducted a GHG emissions assessment?",
      options: [
      { value: "5", label: "Scope 1, 2 & 3 completed with third-party verification", points: 5, reportContext: "Third-party verified inventory provides credibility for carbon credit transactions. You have the data foundation to pursue both high-quality offset procurement (buyer) and potentially project origination (seller) if emission reduction projects exist within your operations." },
      { value: "4", label: "Scope 1, 2 & 3 completed", points: 4, reportContext: "Comprehensive scope coverage is excellent, but lack of verification may limit access to premium carbon credit buyers or registries. Consider pursuing ISO 14064 verification to strengthen your carbon credit strategy's credibility." },
      { value: "3", label: "Scope 1 & 2 completed", points: 3, reportContext: "Scope 3 represents 60-90% of emissions for most organizations. Without this data, you cannot accurately size your long-term carbon credit requirements. Priority recommendation: initiate Scope 3 screening assessment, focusing on purchased goods, capital goods, and downstream emissions." },
      { value: "2", label: "In progress", points: 2, reportContext: "In-progress assessment creates planning uncertainty. Until completion, carbon credit volumes and budgets remain speculative. Recommend establishing preliminary estimates based on revenue-based emission factors while detailed assessment continues." },
      { value: "0", label: "Not started", points: 0, reportContext: "Carbon credit strategy cannot be developed without emissions quantification. This is your critical path item. Estimate timeline: 3-6 months for Scope 1&2, additional 6-12 months for Scope 3 depending on value chain complexity." },
    ],
  },
  // Section 2: Drivers & Motivation (20 points)
    {
      id: "q4",
    domain: "section2",
    text: "What is the primary driver for considering carbon credits?",
      options: [
      { value: "7", label: "Alignment with Vision 2030 / SGI and demonstrating national leadership", points: 7, reportContext: "Strategic alignment with national priorities demonstrates leadership and positions your organization for potential government incentives, partnerships, and recognition programs under SGI. This driver suggests long-term commitment beyond pure compliance." },
      { value: "6", label: "Regulatory anticipation", points: 6, reportContext: "Proactive regulatory positioning is prudent given Saudi Arabia's anticipated carbon pricing mechanisms. Early movers in voluntary markets typically achieve lower credit costs and stronger vendor relationships before mandatory schemes create demand spikes." },
      { value: "5", label: "Access to global carbon markets and new revenue streams", points: 5, reportContext: "Revenue generation focus indicates potential project origination opportunity. If your organization operates energy efficiency, renewable energy, nature-based, or industrial process improvements, these may qualify for carbon credit certification under VCS, Gold Standard, or emerging Saudi registries." },
      { value: "4-offset", label: "Offsetting residual emissions after reduction efforts", points: 4, reportContext: "Viewing credits as residual tools aligns with best practice mitigation hierarchy. This driver suggests mature understanding that credits complement rather than replace reduction. Ensure your reduction pathway is documented to avoid greenwashing allegations." },
      { value: "4-finance", label: "Enhance financial viability / green financing access", points: 4, reportContext: "Green financing linkage is increasingly relevant as Saudi banks adopt ESG lending criteria. Carbon credits can strengthen sustainability-linked loan applications and potentially reduce borrowing costs, but must be paired with credible reduction targets." },
      { value: "3", label: "Client/customer requirements or supply chain pressure", points: 3, reportContext: "Supply chain pressure indicates external rather than internal motivation. While valid, this reactive posture may result in minimum-viable compliance rather than strategic advantage. Consider elevating carbon strategy to competitive differentiator rather than obligation." },
      { value: "2", label: "Reputational management / greenwashing concerns", points: 2, reportContext: "Reputational focus without substantive reduction risks genuine greenwashing. Carbon credits should never be primary climate response. Critical priority: develop authentic reduction roadmap where credits address only unavoidable emissions." },
      ],
    },
    {
      id: "q5",
    domain: "section2",
    text: "Which stakeholder is most influential in your carbon-related decisions?",
      options: [
      { value: "6", label: "Board of Directors with dedicated ESG committee", points: 6, reportContext: "Board-level ESG committee indicates governance maturity and integration with corporate strategy. Carbon credit decisions will benefit from enterprise perspective, but ensure technical expertise exists to evaluate credit quality and avoid reputational risk from low-quality offsets." },
      { value: "5-board", label: "Board of Directors", points: 5, reportContext: "Board engagement ensures strategic alignment but may slow decision velocity. Establish clear delegation thresholds (e.g., Board approves strategy and budget >$X, management executes within parameters) to balance governance with operational agility." },
      { value: "5-ceo", label: "CEO / Executive Management", points: 5, reportContext: "Executive sponsorship accelerates implementation but risks siloed decision-making. Recommend establishing cross-functional carbon credit steering committee including finance, operations, procurement, and sustainability to ensure holistic evaluation." },
      { value: "4-investors", label: "Investors / Lenders with ESG requirements", points: 4, reportContext: "Capital market pressure creates urgency but may prioritize disclosure over substance. Ensure your carbon credit strategy satisfies investor expectations while maintaining environmental integrity—increasingly, sophisticated investors scrutinize credit quality and additionality." },
      { value: "4-regulators", label: "Regulators / Government entities", points: 4, reportContext: "Government influence suggests regulated sector or public entity. Stay closely connected to RCCS (Regional Voluntary Carbon Market Company) developments and potential linkages between voluntary action and future compliance obligations under Saudi carbon pricing." },
      { value: "3", label: "Sustainability / ESG team", points: 3, reportContext: "Sustainability team influence without executive sponsorship often results in pilot programs that don't scale. To elevate carbon credits from initiative to strategy, develop business case quantifying financial impact—carbon pricing risk, green revenue opportunity, cost of inaction." },
      { value: "0", label: "No clear ownership identified", points: 0, reportContext: "Lack of ownership is critical governance gap. Carbon credits involve financial commitments, reputational exposure, and strategic implications requiring executive accountability. Immediate action: assign clear ownership at C-suite or SVP level with Board reporting line." },
      ],
    },
    {
      id: "q6",
    domain: "section2",
    text: "How important are carbon credits in achieving your long-term decarbonisation goals?",
      options: [
      { value: "7", label: "Critical and permanent component of our Net Zero strategy", points: 7, reportContext: "Viewing credits as permanent solution suggests either: (a) genuine hard-to-abate emissions requiring offsets, or (b) over-reliance potentially masking insufficient reduction ambition. Recommendation: ensure at least 90% of 2030 target achieved through direct reduction, with credits addressing only unavoidable residuals to maintain credibility." },
      { value: "6", label: "Important as transitional bridge while developing reduction projects", points: 6, reportContext: "Transitional framing aligns with science-based guidance and demonstrates understanding of evolving best practices. Critical success factor: establish clear timeline and phase-out criteria (e.g., credits <30% of reduction claim by 2030, <10% by 2040) to maintain stakeholder trust." },
      { value: "5", label: "Important but secondary to internal reduction efforts", points: 5, reportContext: "Appropriate prioritization hierarchy. This balanced view enables pragmatic carbon credit use while avoiding substitution of reduction. Ensure internal reduction receives majority of carbon budget allocation—typically recommend 80/20 split: reduction investment vs. offsetting." },
      { value: "4", label: "Tactical tool for residual emissions only", points: 4, reportContext: "Tactical residual focus represents gold-standard approach aligned with SBTi Net Zero guidance. This positioning minimizes greenwashing risk and maximizes authenticity. Residuals typically represent <10% of baseline emissions after aggressive reduction in well-designed strategies." },
      { value: "2", label: "Under evaluation", points: 2, reportContext: "Evaluation stage suggests uncertainty about role and value. Common in organizations without clear Net Zero targets. Recommendation: complete decarbonization pathway modeling first to identify technical and economic abatement limits where carbon credits become necessary versus optional." },
      { value: "0", label: "Not relevant to our decarbonisation approach", points: 0, reportContext: "Rejection of carbon credits is unusual for organizations conducting this assessment. Possible explanations: (a) 100% renewable energy/low-emission business model, (b) philosophical opposition to offsetting, or (c) misunderstanding of credit types. Clarify rationale before proceeding—credits may be appropriate for Scope 3 or residual Scope 1 emissions even with strong reduction plans." },
    ],
  },
  // Section 3: Market Readiness & Trust (25 points)
    {
      id: "q7",
    domain: "section3",
    text: "What role do you play (or anticipate playing) in carbon markets?",
      options: [
      { value: "5-seller", label: "Seller with identified projects", points: 5, reportContext: "Confirmed origination projects position you as supply-side participant. Priority actions: (1) project eligibility assessment against VCS/Gold Standard/ACR methodologies, (2) baseline and monitoring plan development, (3) validation/verification body selection. Saudi Arabia's RCCS may offer streamlined pathways for domestic projects." },
      { value: "4-seller", label: "Seller exploring feasibility", points: 4, reportContext: "Project identification phase requires feasibility screening. High-potential Saudi project types: renewable energy displacement of grid/diesel, energy efficiency in industry/buildings, afforestation/mangrove restoration, methane capture from waste/agriculture, and industrial process improvements (cement, petrochemicals). Conduct preliminary additionality test and financial analysis." },
      { value: "5-buyer", label: "Buyer for offsetting purposes", points: 5, reportContext: "Demand-side position requires procurement strategy addressing: credit vintage preferences, geography (local vs. international), project type alignment with stakeholder values, registry requirements, and volume/budget parameters. Develop approved vendor list and due diligence protocol to ensure quality." },
      { value: "5-both", label: "Both buyer and seller", points: 5, reportContext: "Dual market role creates complexity but also strategic optionality. You can potentially self-supply credits from reduction projects while purchasing external credits for residual emissions. This requires careful accounting to avoid double-counting and clear segregation of generated vs. purchased credits in reporting." },
      { value: "4-intermediary", label: "Intermediary / facilitator", points: 4, reportContext: "Facilitator role suggests service provider, trading platform, or advisory position. Your carbon credit strategy likely focuses on market development, matchmaking, and transaction support rather than direct offset liability. Key success factors: trust-building, quality assurance capabilities, and understanding of both buyer and seller perspectives." },
      { value: "1", label: "Undecided", points: 1, reportContext: "Role uncertainty inhibits strategy development. Decision drivers: If emissions >10,000 tCO2e and reduction potential exists, consider origination; if emissions significant but limited internal abatement options, plan for procurement; if emissions minimal, carbon credit strategy may be premature." },
      ],
    },
    {
    id: "q8",
    domain: "section3",
    text: "What concerns you most about carbon credits?",
      options: [
      { value: "5-credibility", label: "Credibility / quality of credits", points: 5, reportContext: "Quality concern demonstrates sophistication and awareness of market controversies (e.g., rainforest credits, over-crediting). Mitigation strategies: (1) prioritize removal credits over avoidance, (2) require third-party validation/verification, (3) select projects with co-benefits (SDG alignment), (4) review credit rating services (BeZero, Calyx Global, Sylvera), (5) prefer technology-based credits (CCUS, DAC) where appropriate." },
      { value: "5-greenwashing", label: "Greenwashing risk and reputational damage", points: 5, reportContext: "Reputational sensitivity is appropriate given increasing scrutiny from regulators, NGOs, and media. Protection strategies: (1) maintain 90/10 reduction-to-offset ratio in claims, (2) transparent disclosure of credit types and volumes, (3) avoid 'carbon neutral' claims unless genuine Net Zero, (4) third-party assurance of carbon claims, (5) align with emerging guidance (VCMI Claims Code, Oxford Principles)." },
      { value: "4-volatility", label: "Carbon credit price volatility", points: 4, reportContext: "Price risk is material consideration. Historical range: $5-150/tCO2e depending on credit type. Hedge strategies: (1) forward contracts with suppliers, (2) portfolio approach mixing low-cost avoidance credits with higher-quality removals, (3) phase credit procurement over time rather than spot purchases, (4) internal carbon price mechanism to create budget predictability." },
      { value: "4-cost", label: "Long-term cost uncertainty and budget impact", points: 4, reportContext: "Budget impact concern suggests CFO/finance perspective. Recommended approach: scenario modeling of three price paths (low: $15/tCO2e, medium: $35/tCO2e, high: $75/tCO2e) over 10-year horizon to quantify financial exposure. Build carbon budget line item into annual planning with inflation escalator." },
      { value: "4-expertise", label: "Lack of internal expertise and decision-making capability", points: 4, reportContext: "Capability concern is most addressable barrier. Build internal expertise through: (1) staff training (IETA, Gold Standard, ICROA courses), (2) advisory engagement for initial transactions, (3) recruiting carbon market specialist, (4) peer learning through industry associations. Consider 12-18 month capability-building roadmap before large commitments." },
      { value: "3-regulatory", label: "Regulatory uncertainty", points: 3, reportContext: "Voluntary-compliance linkage question is particularly relevant in Saudi context given anticipated carbon pricing. Current guidance: do not assume voluntary credits will be accepted for future compliance—treat as separate programs. However, early voluntary action demonstrates commitment and builds internal capability for compliance readiness." },
      { value: "3-local", label: "Limited availability of local Saudi projects", points: 3, reportContext: "Saudi project scarcity is current reality but changing rapidly. RCCS aims to catalyze domestic supply, and SGI commitments (10bn trees, 50% renewables, circular carbon economy) will generate certifiable projects. Near-term strategy: accept international credits while monitoring domestic pipeline. Medium-term: set target for >50% local sourcing by 2027." },
      { value: "2", label: "Complex verification and certification processes", points: 2, reportContext: "Process concern suggests administrative burden focus. Reality: initial verification is intensive, but ongoing annual verification becomes routine. Consider engaging carbon credit advisory for first project (if originator) or first procurement (if buyer) to build institutional knowledge, then internalize process for subsequent transactions." },
      { value: "1", label: "No significant concerns", points: 1, reportContext: "Lack of concern may indicate: (a) high confidence and experience, (b) insufficient exposure to market challenges, or (c) low materiality of carbon credits to business. If (b), recommend structured risk assessment reviewing quality, cost, regulatory, and reputational dimensions before significant commitments." },
      ],
    },
    {
    id: "q9",
    domain: "section3",
    text: "If you are a Buyer, which type of carbon credits would your organisation prefer?",
      options: [
      { value: "5-nature-co", label: "Nature-based solutions with strong co-benefits", points: 5, reportContext: "Co-benefit prioritization aligns with emerging best practices and SGI's holistic sustainability vision. High-quality options: mangrove restoration (Saudi coasts), agroforestry (Al-Ahsa), community forestry (Asir). Co-benefits strengthen stakeholder narrative but typically command 20-40% price premium. Budget: $25-75/tCO2e." },
      { value: "4-nature", label: "Nature-based solutions focused purely on carbon sequestration", points: 4, reportContext: "Pure carbon focus enables cost efficiency but may miss storytelling opportunity. Consider whether your stakeholders (customers, investors, employees) value biodiversity, water, or community outcomes—if yes, pivot to co-benefit projects. If purely carbon focus appropriate, expect: $15-35/tCO2e for afforestation/reforestation." },
      { value: "5-tech-removal", label: "Technology-based carbon removal", points: 5, reportContext: "Carbon removal preference demonstrates scientific rigor and understanding of permanence distinction. Premium quality position suitable for organizations with high climate leadership ambitions or net-negative goals. Saudi opportunities: CCUS projects in oil/gas sector (Aramco, SABIC pilots), potential DAC projects under circular carbon economy initiatives. Budget: $100-300+/tCO2e currently, declining over time." },
      { value: "4-tech-avoid", label: "Technology-based emissions avoidance", points: 4, reportContext: "Avoidance credits (renewable energy displacing fossil generation) are lower-cost but face growing additionality scrutiny—are they truly additional or would projects happen anyway? Suitable for transition period while market matures. Saudi context: solar/wind projects may struggle additionality test given ambitious government renewable targets. Budget: $8-20/tCO2e." },
      { value: "5-hybrid", label: "Hybrid portfolio", points: 5, reportContext: "Portfolio approach balances cost, quality, and risk—recommended strategy. Example mix: 40% nature-based (mangroves, afforestation) for stakeholder engagement, 40% technology avoidance (renewable energy, methane) for volume and cost, 20% carbon removal (CCUS, biochar) for quality signal. Blended cost: $25-45/tCO2e." },
      { value: "5-local", label: "Local KSA-based projects", points: 5, reportContext: "Local preference strongly aligns with Vision 2030 and creates authentic national contribution narrative. Current challenge: limited Saudi project supply. Strategy: engage RCCS, identify domestic project developers, potentially co-invest in project development to secure future supply. Accept 30-50% premium over international credits to prioritize local impact." },
      { value: "4-intl", label: "International projects with Gold Standard / VCS certification", points: 4, reportContext: "Registry certification (Gold Standard, VCS) provides quality baseline and third-party validation. Suitable approach if local supply unavailable or insufficient. Recommend geographic diversification (MENA region, African renewable energy, Asian nature-based) to demonstrate global citizenship while maintaining cultural relevance." },
      { value: "2", label: "Lowest cost per tonne regardless of type", points: 2, reportContext: "Pure cost minimization creates significant quality and reputational risk. Cheap credits ($5-15/tCO2e) typically have weak additionality, limited permanence, or verification concerns. This approach may satisfy near-term budget but exposes to future allegations of greenwashing or credit write-offs. Recommend establishing quality floor: minimum Gold Standard or VCS certification, avoid credits rated D/E by rating agencies." },
      { value: "1", label: "Unsure / need guidance", points: 1, reportContext: "Uncertainty is appropriate at early stage. Decision framework: (1) Define stakeholder priorities (cost vs. quality vs. local vs. co-benefits), (2) Set budget parameters, (3) Review portfolio options aligning priorities and budget, (4) Pilot with small volume (100-1,000 tCO2e) before scaling. Engage broker or advisor for first transaction to build confidence." },
      ],
    },
    {
    id: "q10",
    domain: "section3",
    text: "If you are a Seller/Originator, are you aware which type of projects are eligible for Carbon Credits?",
      options: [
      { value: "5", label: "Comprehensive understanding across multiple project types", points: 5, reportContext: "Comprehensive project awareness positions you well for opportunity assessment. Next steps: (1) internal asset inventory mapping emissions sources and reduction initiatives against eligible methodologies, (2) financial feasibility analysis comparing carbon credit revenue vs. certification costs, (3) prioritization matrix ranking projects by credit volume potential, cost to certify, and co-benefits." },
      { value: "3-nature", label: "Aware of nature-based options", points: 3, reportContext: "Nature-based focus appropriate for organizations with land assets. Saudi-relevant opportunities: mangrove restoration (East/West coasts), afforestation/reforestation (highland areas), rangeland management (desert ecosystem restoration). Key considerations: baseline establishment, permanence risk (fire, disease), long verification timelines (5-10 years first credit issuance). Expand awareness to technical methodologies as complement." },
      { value: "3-tech", label: "Aware of technology-based options", points: 3, reportContext: "Technology focus suits industrial organizations. High-potential Saudi applications: solar/wind displacing diesel generators (remote facilities), CCUS on industrial emissions (cement, petrochemicals, oil/gas), energy efficiency projects (building retrofits, process optimization), fuel switching (diesel to natural gas). Additionality challenge: demonstrate project wouldn't occur under business-as-usual. Expand awareness to nature-based options for portfolio diversification." },
      { value: "3-industrial", label: "Aware of industrial/waste options", points: 3, reportContext: "Industrial focus indicates manufacturing, oil/gas, or utility sector. Prime candidates: landfill gas capture, wastewater treatment methane reduction, flaring reduction, industrial refrigerant destruction, cement clinker substitution. These projects often have strong additionality case and measurable baselines. Expand awareness to other categories to maximize revenue opportunity." },
      { value: "2", label: "Limited understanding / single project type only", points: 2, reportContext: "Limited project knowledge constrains opportunity identification. Recommended capacity building: (1) methodology database review (Verra VCS, Gold Standard), (2) peer benchmarking (sector peers' certified projects), (3) consultant-led opportunity assessment. Initial focus: energy-related projects (easiest to quantify) before progressing to complex categories like nature-based or agriculture." },
      { value: "0", label: "Not aware of eligible project types", points: 0, reportContext: "Project eligibility gap is fundamental barrier to origination. Priority action: structured training on carbon credit project cycle—project identification, methodology selection, baseline setting, monitoring plans, validation, verification, credit issuance. Estimated learning curve: 3-6 months to develop organizational competency. Consider starting with advisor-led pilot project to build knowledge while generating first credits." },
      ],
    },
    {
    id: "q11",
    domain: "section3",
    text: "Would your organisation prefer local Saudi carbon credit projects over international ones?",
      options: [
      { value: "5", label: "Strongly prefer local with price premium willingness", points: 5, reportContext: "Premium willingness demonstrates authentic commitment to domestic market development and Vision 2030 alignment. This positioning differentiates your organization as climate leader and supports RCCS market-building objectives. Procurement strategy: pre-purchase agreements with Saudi project developers (mangrove restoration, afforestation, renewable energy), co-investment in project development, premium tolerance: 20-50% above international equivalents." },
      { value: "4-strong", label: "Strongly prefer local but price-sensitive", points: 4, reportContext: "Local preference with price constraint is pragmatic. Recommended approach: set local sourcing target (e.g., 70% local by 2027) with declining premium tolerance (start 30%, reduce 5% annually) to incentivize local market maturation while maintaining budget discipline. This creates predictable demand signal for domestic developers." },
      { value: "4-prefer", label: "Prefer local if available and competitively priced", points: 4, reportContext: "Conditional local preference allows flexibility while supporting domestic market. Strategy: equal-weighted scoring matrix—e.g., 40% price, 30% quality/co-benefits, 30% local content. This ensures local projects compete fairly without automatic preference but receive credit for national contribution. Transparent criteria strengthen procurement governance." },
      { value: "3", label: "Neutral—quality matters more than geography", points: 3, reportContext: "Geography-neutral quality prioritization is defensible position emphasizing environmental integrity over origin. Suitable for organizations with global operations or international stakeholder base. However, consider whether modest local preference (10-20% scoring weighting) could strengthen Vision 2030 narrative without materially compromising quality standards." },
      { value: "2", label: "Prefer international for cost/availability reasons", points: 2, reportContext: "International preference likely driven by current supply gap or cost considerations. Valid near-term given limited Saudi project inventory, but monitor market evolution—RCCS, SGI investments, and NEOM projects will accelerate domestic supply. Recommend setting timeline: 100% international acceptable through 2025, transition to minimum 30% local by 2028 as supply emerges." },
      { value: "1", label: "No preference whatsoever", points: 1, reportContext: "Complete indifference unusual given strategic importance of Vision 2030 alignment in Saudi context. Recommendation: engage stakeholders (Board, leadership, customers, employees) to assess whether local preference creates strategic value. Even small local allocation (20-30%) can strengthen national contribution narrative at minimal cost premium." },
    ],
  },
  // Section 4: Economics & Decision-Making (20 points)
  {
    id: "q12",
    domain: "section4",
    text: "What carbon price range would your organisation consider acceptable (USD/tonne)?",
      options: [
      { value: "7", label: "$100+", points: 7, reportContext: "Premium pricing commitment signals highest climate leadership tier and focus on carbon removal (CCUS, DAC, biochar, enhanced weathering) over avoidance. This positioning suitable for organizations with: net-negative goals, high reputational standards, limited emissions (cost is manageable), or luxury/premium brand requiring quality consistency. At $100+/tCO2e, budget 2-5x industry average—ensure stakeholder alignment on this strategic choice." },
      { value: "6", label: "$50-100", points: 6, reportContext: "Upper-middle pricing enables quality-focused portfolio balancing permanence and cost. Recommended mix: 60% avoidance (nature-based with co-benefits, renewable energy) at $20-40/tCO2e, 40% removal (biochar, CCUS) at $80-150/tCO2e, blended average: $60-80/tCO2e. This range positions organization as quality-conscious while maintaining budget discipline." },
      { value: "5", label: "$25-50", points: 5, reportContext: "Mid-range pricing reflects industry mainstream and enables strong quality standards without premium positioning. Optimal portfolio: 80% avoidance (high-quality nature-based and technology), 20% removal or co-benefit premium, blended: $30-45/tCO2e. Sufficient budget for Gold Standard/VCS certification, third-party validation, and co-benefit projects. Adequate for most stakeholder expectations." },
      { value: "3", label: "$10-25 (cost-efficient avoidance focus)", points: 3, reportContext: "Lower-middle pricing limits to avoidance credits with modest quality standards. Achievable through: renewable energy displacement ($8-15), cookstove projects ($10-18), landfill gas ($12-20), reforestation without co-benefits ($15-25). Risk: tighter scrutiny on additionality, limited permanence assurance, constrained co-benefit storytelling. Suitable for cost-sensitive organizations but requires careful quality controls to avoid reputational exposure." },
      { value: "1", label: "<$10 (budget-constrained minimum compliance)", points: 1, reportContext: "Sub-$10 pricing restricts to lowest-tier credits with highest risk profile. Typically: avoided deforestation with weak baselines, renewable energy in subsidy-rich markets, aged vintage credits (pre-2015). This budget may satisfy near-term compliance at minimum cost but creates: significant greenwashing risk, potential credit write-off if quality challenged, weak stakeholder narrative. Not recommended except for pure financial compliance in low-scrutiny contexts." },
      { value: "2", label: "Not assessed yet / need cost modeling", points: 2, reportContext: "Unassessed pricing is acceptable at early stage but must be resolved before procurement. Cost modeling approach: (1) Quantify offset requirement (tCO2e), (2) Research 10-year price forecasts by credit type, (3) Model three scenarios (optimistic/expected/pessimistic), (4) Calculate NPV of carbon liability, (5) Establish budget range with contingency. Engage finance/treasury to integrate into capital planning." },
      ],
    },
    {
    id: "q13",
    domain: "section4",
    text: "Who would approve carbon credit purchases in your organisation?",
      options: [
      { value: "6", label: "Board of Directors", points: 6, reportContext: "Direct Board approval indicates highest governance level, appropriate for: material financial commitments (>$1M annual), reputational risk exposure, strategic climate positioning, or early-stage market uncertainty. Benefit: strong accountability and alignment with corporate strategy. Challenge: decision velocity—may require 4-6 weeks per transaction. Establish delegated thresholds to enable operational agility within Board-approved framework." },
      { value: "5-board", label: "Board (threshold-based)", points: 5, reportContext: "Threshold-based escalation balances governance with efficiency. Recommended structure: Board approves carbon credit strategy, annual budget, and quality standards; management executes within parameters; transactions >$500K or novel credit types return to Board. This enables routine procurement speed while maintaining oversight of material commitments." },
      { value: "5-exec", label: "CEO / CFO", points: 5, reportContext: "C-suite authority appropriate for organizations with mature climate governance. Success factors: ensure CFO and CEO alignment (climate commitment vs. cost management), establish cross-functional input mechanism to avoid siloed decisions, document decision criteria for consistency, and maintain Board visibility through quarterly reporting even if approval not required." },
      { value: "5-committee", label: "Cross-functional Carbon Committee", points: 5, reportContext: "Carbon Committee model is emerging best practice for organizations with material emissions and ongoing offset needs. Recommended composition: CFO/Finance (budget), CSO/Sustainability (strategy/quality), COO/Operations (integration), CLO/Legal (compliance), CCO/Communications (reputation). Committee benefits: diverse perspectives, faster decisions than Board, clear accountability. Establish: charter, decision thresholds, meeting cadence." },
      { value: "3", label: "Sustainability / ESG team", points: 3, reportContext: "Sustainability team authority indicates operational execution role but may signal insufficient cross-functional integration. Risk: sustainability priorities (quality, co-benefits, local preference) may conflict with financial constraints, creating frustration or sub-optimal decisions. Strengthen governance by: establishing steering committee with finance/operations input, documenting decision criteria balancing sustainability and financial objectives, requiring CFO co-approval above $100K." },
      { value: "2", label: "Procurement team", points: 2, reportContext: "Procurement authority treats carbon credits as commodity transaction, which oversimplifies strategic and reputational dimensions. Procurement role should be execution (vendor management, contracting, payment) not decision (credit type, quality standards, volume). Realign governance: strategy and standards set by sustainability/ESG with executive endorsement, procurement executes within approved framework." },
      { value: "0", label: "No formal approval process established", points: 0, reportContext: "Absence of approval process is critical governance gap that will delay implementation and create confusion. Carbon credit purchases involve: financial commitments (potentially millions annually), reputational exposure (greenwashing risk), strategic implications (Net Zero pathway). Immediate action: draft decision authority matrix (RACI), identify approvers by transaction size and type, obtain leadership endorsement of governance structure." },
      ],
    },
    {
    id: "q14",
    domain: "section4",
    text: "How do you view carbon credits financially?",
      options: [
      { value: "7-brand", label: "Strategic investment in brand value and stakeholder trust", points: 7, reportContext: "Brand investment framing elevates carbon credits from cost to value creation. Quantify returns: premium pricing potential (sustainable products command 5-20% premiums), talent attraction (climate-conscious workforce), customer loyalty (B2B procurement preference), investor access (ESG funds). Calculate brand value uplift and carbon cost per stakeholder impression—often favorable vs. traditional marketing spend. This framing strengthens CFO business case." },
      { value: "7-pathway", label: "Strategic investment in long-term decarbonization pathway", points: 7, reportContext: "Long-term pathway investment framing demonstrates strategic climate commitment beyond compliance. Financial logic: carbon credits enable Net Zero achievement while reduction infrastructure (renewable PPAs, fleet electrification, process redesign) scales up. This avoids delay cost—waiting for 100% reduction before claiming progress. Key: ensure credits are truly transitional with declining volume over time, not substitution for reduction." },
      { value: "6", label: "Risk management tool", points: 6, reportContext: "Risk tool perspective demonstrates financial sophistication and forward-looking mindset. Quantifiable risks hedged: (1) future carbon pricing (Saudi Arabia's anticipated compliance mechanism), (2) stranded asset risk (carbon-intensive assets face valuation discount), (3) customer attrition (procurement standards increasingly require carbon performance), (4) regulatory penalty (if voluntary commitments formalized). Model risk-adjusted ROI comparing credit cost vs. potential exposure." },
      { value: "4", label: "Compliance cost", points: 4, reportContext: "Compliance framing is accurate if carbon credits address existing commitment (Net Zero pledge, customer requirement, loan covenant) but may indicate reactive posture. Strengthen business case by identifying compliance cost-avoidance—credits often cheaper than non-compliance alternatives: premium paid for non-sustainable product loss, contract penalties, regulatory fines. Demonstrate credits are least-cost compliance pathway." },
      { value: "3-opex", label: "Operational expense", points: 3, reportContext: "OpEx classification is standard accounting treatment but may limit budget allocation and strategic consideration. Recommendation: while maintaining OpEx accounting, develop supplementary business case framing carbon credits as value-protection (defending revenue/reputation) rather than pure cost. This dual view helps secure adequate budget allocation even in cost-reduction cycles." },
      { value: "3-temp", label: "Temporary solution until better alternatives are available", points: 3, reportContext: "Transitional view is appropriate if paired with reduction plan but concerning if indefinite. Carbon credits should decrease over time as reduction scales—if not, it suggests avoidance of reduction investment. Financial implication: budget carbon costs for 10-15 years with declining volumes (e.g., 100% offset in 2025, 50% in 2030, 10% in 2035, 0% in 2040). Ensure parallel budget for reduction CapEx exceeds carbon credit OpEx." },
      { value: "1", label: "Sunk cost with unclear ROI", points: 1, reportContext: "Unclear ROI perception indicates weak business case or poor stakeholder communication. Carbon credit value is often intangible (reputation, risk avoidance, stakeholder trust) making traditional ROI calculation challenging. Reframe: instead of direct ROI, quantify cost of inaction—revenue at risk from customer attrition, valuation discount from ESG underperformance, opportunity cost of delayed climate positioning. Defensive value case often stronger than offensive ROI case." },
      { value: "2", label: "Not yet determined / under financial assessment", points: 2, reportContext: "Undetermined financial view appropriate at assessment stage. Financial characterization approach: (1) Quantify magnitude (annual tCO2e × price = $X), (2) Assess materiality (% of revenue, % of operating expense), (3) Compare to alternatives (cost to reduce internally vs. offset), (4) Evaluate risk profile (price volatility, regulatory uncertainty), (5) Determine appropriate accounting treatment and approval level. Complete before significant commitments." },
    ],
  },
  // Section 5: Future Outlook (20 points)
  {
    id: "q15",
    domain: "section5",
    text: "When do you expect carbon credits to become material for your organisation?",
      options: [
      { value: "7", label: "Already material", points: 7, reportContext: "Current materiality indicates your organization is carbon market participant with active experience. Focus shifts from strategy development to optimization: portfolio refinement (balancing cost/quality/local content), vendor diversification (avoiding concentration risk), process efficiency (streamlining procurement/verification), and stakeholder communication (transparent disclosure, impact reporting). Consider sharing lessons learned to support peer organizations entering market." },
      { value: "6", label: "Within 1 year", points: 6, reportContext: "1-year horizon creates implementation urgency. Critical path over next 12 months: (1) Finalize carbon credit policy (volumes, budget, quality standards, procurement process), (2) Conduct market engagement (RFPs to brokers, project developers), (3) Execute pilot transaction (small volume to test process), (4) Establish internal systems (accounting, inventory management, disclosure), (5) Prepare stakeholder communication (website content, sustainability report). Recommend dedicated project manager given timeline intensity." },
      { value: "5", label: "Within 1-2 years", points: 5, reportContext: "1-2 year timeframe enables thoughtful strategy development without excessive delay. Recommended phasing: Year 1 (education, strategy, governance, pilot 5-10% of eventual volume), Year 2 (scale procurement/origination to full requirement). This pacing allows learning from market evolution, pilot transaction lessons, and peer experience. Begin early stakeholder engagement to secure buy-in before material financial commitments." },
      { value: "3", label: "Within 3-5 years", points: 3, reportContext: "3-5 year horizon suggests either: (a) low current emissions requiring limited offsets near-term, or (b) ambitious reduction plans delaying offset need, or (c) regulatory timeline driving compliance preparation. All valid, but consider acceleration drivers: customer pressure may intensify faster than expected, Saudi regulations may formalize sooner (RCCS development), first-mover advantages in credit access/pricing. Maintain monitoring cadence to adjust timeline as market evolves." },
      { value: "1", label: "Beyond 5 years", points: 1, reportContext: "Beyond-5-year view indicates low priority or unclear relevance. This extended timeline creates risks: (1) late market entry may face constrained supply and higher costs, (2) stakeholder expectations may shift faster than anticipated, (3) regulatory compliance deadlines may be missed. Recommendation: even with long-term materiality view, begin foundational education and monitoring to avoid being caught unprepared by market/regulatory acceleration." },
      { value: "0", label: "Not expected to be material", points: 0, reportContext: "No-materiality expectation is unusual for organizations completing this assessment. Possible scenarios: (1) near-zero emissions business model (digital, service-based with renewable energy), (2) 100% reduction pathway with no residuals, (3) philosophical opposition to offsetting. Validate this assumption—most organizations discover unavoidable Scope 3 emissions or hard-to-abate Scope 1 sources requiring some level of offsetting even with aggressive reduction. Recommend completing full Scope 1-3 inventory before confirming no-materiality conclusion." },
      ],
    },
    {
    id: "q16",
    domain: "section5",
    text: "What would accelerate your organisation's adoption of carbon credits?",
      options: [
      { value: "7-mandate", label: "Executive mandate or Board directive", points: 7, reportContext: "Leadership directive is most powerful accelerator. If Board/CEO mandate exists, implementation timeline compresses from 12-18 months to 6-9 months. Success factors post-mandate: (1) clear objectives and timeline from leadership, (2) dedicated budget allocation, (3) empowered project team with cross-functional representation, (4) regular progress reporting to maintain momentum. Leverage mandate to overcome organizational inertia and secure resources." },
      { value: "6-partner", label: "Availability of trusted implementation partner", points: 6, reportContext: "Partner need indicates desire to de-risk implementation through expertise access. Partner types by need: (1) Advisory/consulting (strategy, governance, quality standards)—Typically 3-6 month engagement, $50-200K, (2) Carbon credit broker (procurement execution, portfolio management)—Commission-based 5-15% of transaction, (3) Registry/certification body (origination projects)—Project-specific fees $50-500K depending on size. Partner selection criteria: sector experience, Saudi market knowledge, client references, fee transparency." },
      { value: "6-capability", label: "Internal capability building", points: 6, reportContext: "Capability building most sustainable accelerator creating long-term organizational competency. Capability development plan: (1) Core team training (IETA, Gold Standard courses, 2-5 days, $2-5K/person), (2) Dedicated FTE hire or allocation (Carbon Manager role, sustainability/finance background, $80-150K annual), (3) Peer learning (industry association participation, conference attendance), (4) Advisory support for first transaction. Investment: $150-300K Year 1, $100-150K ongoing." },
      { value: "5-regulatory", label: "Clear regulatory framework in Saudi Arabia", points: 5, reportContext: "Saudi regulatory framework development is external factor but monitoring creates preparedness. RCCS and SAMA initiatives will provide clarity on: voluntary credit treatment in future compliance, local project certification pathways, transaction infrastructure (registries, exchanges), tax treatment, and international credit eligibility. Recommendation: maintain regulatory monitoring through industry associations and engage in consultation processes to influence framework design." },
      { value: "4-peer", label: "Success stories from peer organizations", points: 4, reportContext: "Peer demonstration addresses uncertainty and risk aversion. Action items: (1) Identify 3-5 comparable organizations (sector, size, market) with carbon credit experience, (2) Request case study sharing through industry associations, (3) Conduct peer benchmarking calls to understand lessons learned, (4) Develop internal case study translating peer experiences to your context. Peer insights often more credible to skeptical executives than consultant recommendations." },
      { value: "4-quality", label: "Improved carbon credit quality and transparency", points: 4, reportContext: "Quality improvement is external market evolution factor. Positive developments: growth in carbon ratings (BeZero, Sylvera, Calyx Global) providing independent quality scores, increased methodology rigor (Verra, Gold Standard updates), enhanced monitoring technology (satellite verification, IoT sensors), and disclosure platforms (CDM Registry, AlliedOffsets). Strategy: wait-and-see delays market entry; better approach: engage with evolving quality standards and adjust portfolio as tools improve." },
      { value: "3-price", label: "Lower carbon credit prices", points: 3, reportContext: "Price sensitivity as primary accelerator suggests weak business case or limited climate commitment. Challenge: waiting for price decline may be counterproductive—high-quality credits likely to appreciate as demand (Net Zero commitments) exceeds supply, while cheap credits carry disproportionate quality risk. Alternative approach: accept current pricing for modest volume (pilot 10-20% of need) to build experience, maintain price monitoring for scaling decision, focus quality over cost to protect reputation." },
      { value: "3-pressure", label: "Customer or investor pressure", points: 3, reportContext: "External driver reliance indicates reactive vs. proactive posture. While customer/investor pressure is valid catalyst, waiting for external force creates: delayed entry (higher costs, limited supply), weaker competitive positioning, lost first-mover narrative. Recommendation: preempt external pressure by proactive engagement—survey customers on carbon expectations, engage investors on ESG priorities, assess peer actions. Build internal case before external pressure mandates response." },
      { value: "5-local", label: "More available local Saudi projects", points: 5, reportContext: "Local project availability is legitimate barrier given current Saudi market nascency. Near-term strategy: begin with international credit procurement to build capability and meet immediate needs while monitoring RCCS pipeline for Saudi projects. Engage potential local projects early (co-investment, offtake agreements) to secure future supply. Acceptable to start 100% international with goal of 50%+ local by 2027-2028 as domestic supply scales." },
      { value: "7-ready", label: "Nothing—ready to proceed", points: 7, reportContext: "Readiness indication is most positive signal. Recommend structured implementation: (1) Month 1-2: Finalize procurement policy and approval process, (2) Month 2-3: Issue RFP and vendor selection, (3) Month 3-4: Execute pilot transaction (10-20% of annual need), (4) Month 4-6: Evaluate pilot, refine approach, (5) Month 6-12: Scale to full requirement. Maintain momentum by assigning clear ownership, setting milestone deadlines, and maintaining executive visibility." },
      ],
    },
    {
    id: "q17",
    domain: "section5",
    text: "Would you like guidance on integrating carbon credits into a broader decarbonisation strategy?",
      options: [
      { value: "6-immediate", label: "Yes – immediately", points: 6, reportContext: "Immediate guidance need indicates readiness and urgency. Recommended advisory scope: (1) Decarbonization pathway modeling (abatement cost curve, reduction scenarios), (2) Carbon credit strategy (role in pathway, volumes, budget, quality standards), (3) Procurement/origination roadmap (timeline, governance, vendor engagement), (4) Implementation support (pilot transaction execution). Typical engagement: 3-6 months, $75-250K depending on complexity. Select advisors with: Saudi market knowledge, sector expertise, registry/certification relationships." },
      { value: "5", label: "Yes – within next 6 months", points: 5, reportContext: "6-month timeline allows for strategic preparation before advisory engagement. Pre-engagement actions to maximize advisory value: (1) Complete GHG inventory (Scope 1-3), (2) Conduct preliminary abatement opportunity identification, (3) Define business objectives for carbon credits (compliance, reputation, cost management), (4) Secure budget allocation, (5) Identify key stakeholders and decision-makers. This preparation reduces advisory timeline and cost while increasing implementation success." },
      { value: "4", label: "Yes – within next 12 months", points: 4, reportContext: "12-month horizon provides adequate time for capability building before external support. Self-directed preparation over next year: (1) Team training on carbon markets and credits, (2) Peer benchmarking and case study review, (3) Market monitoring (credit prices, project types, regulatory developments), (4) Internal stakeholder education and alignment. Engage advisors after internal foundation built for higher-impact, focused support on execution vs. education." },
      { value: "2", label: "Maybe – need to assess internal priorities first", points: 2, reportContext: "Priority assessment is prudent first step. Decision framework: Is carbon credit strategy material to business? (emissions >10,000 tCO2e, Net Zero commitment, customer/investor pressure, regulatory exposure). If yes, elevate priority; if no, defer but maintain monitoring. Carbon credit strategy is typically material for: large organizations (>$100M revenue), industrial/energy/transport sectors, B2B businesses with procurement standards, publicly traded or PE-backed companies with ESG expectations." },
      { value: "6-expert", label: "No – have internal expertise", points: 6, reportContext: "Internal capability indicates organizational maturity and prior carbon market experience. Focus shifts from strategy development to execution optimization and continuous improvement. Consider selective advisory on: emerging areas (carbon removal technologies, nature-based co-benefits), market developments (Saudi regulatory changes, new methodologies), or specialized needs (origination project development, portfolio optimization). Even expert organizations benefit from external perspectives on evolving best practices." },
      { value: "0", label: "No – carbon credits not strategic priority", points: 0, reportContext: "Non-priority status requires validation. Carbon credits may be immaterial if: (1) near-zero emissions (<1,000 tCO2e), (2) 100% renewable energy with minimal Scope 3, (3) no Net Zero commitment or customer requirements. However, if material emissions exist and climate strategy is developing, carbon credits may become priority as strategy matures. Recommendation: complete climate strategy development (Net Zero target, reduction pathway) then reassess carbon credit role rather than dismissing prematurely." },
    ],
  },
];

export const questionsData: Record<"en" | "fr" | "ar", Question[]> = {
  en: questionsEn,
  fr: questionsEn,
  ar: questionsEn,
};
